### ISSUE TITLE
Add smooth scrolling

### ISSUE THREAD

**Issue by lokmanm** [lucky-media/luckymedia.mk#34]

**Comment by lokmanm** [comment]
Duti ke `/source/_assets/sass/main.scss` shtoe ket mbas importeve.

```css
html {
  scroll-behavior: smooth;
}
```
